site_name: Mila Technical Documentation
# TODO: it might be possible to use something like
# https://docs.mila.quebec/en/401/ as the site_url to avoid relying on relative
# paths in the doc (../resource instead of /resource)
site_url: https://docs.mila.quebec
repo_name: mila-docs
repo_url: https://github.com/mila-iqia/mila-docs
docs_dir: docs
edit_uri: edit/master/docs/

copyright: >
  Copyright &copy; 2026 Mila –
  <a href="#__consent">Change cookie settings</a>
watch:
  - includes
theme:
  icon:
    admonition:
      wip: fontawesome/solid/brush
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.footer
    - navigation.tracking # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking
    - navigation.sections
    ## Don't auto- expand until maybe after we reorganize the content a bit.
    ## Atm it's too many pages all at once, and doesn't match the sphinx structure.
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true # line numbers on all code blocks (start at 1)
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration
      alternate_style: true
  - toc:
      permalink: true

extra:
  footer_sections:
    - name: "About us"
      link: docs/home/teams
    - name: "Support"
      link: docs/help
  office_hours:
    location: Lab A
    dates:
      - start: 3pm
        end: 5pm
        day: Tuesday
      - start: 2pm
        end: 4pm
        day: Wednesday

  analytics:
    provider: google
    property: G-2SSH8HHK4L
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  consent:
    title: Cookie consent
    description: >-
      We use cookies 🍪 to see which pages get the most love 💜, what folks
      search for 🔍, and what gets downloaded 📥 — all anonymous, zero personal
      data, no device or location tracking. With your consent, you're helping us
      make the docs better.
    actions:
      - accept
      - reject
      - manage

extra_css:
  - stylesheets/extra.css

hooks:
  - hooks/copy_office_hours.py
  - docs/hooks/external_links.py
  - docs/hooks/skill_tags.py
  - docs/hooks/sitemap_exclude.py

plugins:
  - meta
  # privacy plugin currently breaks giscus comments
  # - privacy
  - search
  - include-markdown:
      dedent: true
  - literate-nav:
      nav_file: README.md
  # TODO: It would be interesting to test this but it currently crash with:
  # AttributeError: 'OptimizePlugin' object has no attribute 'pool'
  # - optimize:
  #     optimize_include:
  #       - screenshots/*
