name: Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          # https://github.com/astral-sh/setup-uv?tab=readme-ov-file#github-authentication-token
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run rumdl
        run: uv run rumdl check .
